services:
  - type: web
    name: social-demand-predictor-backend
    env: java
    plan: free
    region: oregon
    branch: main
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/social-demand-predictor-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
